<a href="https://colab.research.google.com/github/GoldKodo/aiphython/blob/main/20240503.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#넘파이 쓰는 이유 ? 큰 배열과 행렬 연산에 필요한 다양한 함수를 제공

#넘파이 설치 명령어 : pip install numpy < 파이썬에서

#기본 설정 : import numpy as np

#넘파이 버전 확인:
#import numpy as np  >  as xx == xx라는 별칭으로 쓰겠다
#print(np.__version__)

#별칭을 사용하는 이유? 코드를 간결하게 만들고 패키지 이름을 줄임

#from numpy import function_name >> 모듈에서 특정 함수만 가져옴


In [2]:
import numpy as np

#np.arange(): 일정한 간격의 값들을 가진 배열 생성
arr = np.arange(10)
print(arr)

arr1 = np.arange(2, 20, 2) # 2부터 19까지, 간격은 2
print(arr1)

#np.zeros(): 모든 값이 0인 배열 생성 / zeros 대신 ones  는 모든 값이 1인 배열 생성
zeros_1d = np.zeros(5)
print(zeros_1d)

#np.random.rand() = 무작위 값 생성
arr_1d = np.random.rand(5)
print(arr_1d)

#np.linspace(): 지정한 범위 내에서 균일한 간격의 값들을 가진 배열 생성

# 0부터 1까지 5개의 값
arr2 = np.linspace(0,1,5)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18]
[0. 0. 0. 0. 0.]
[0.54917463 0.57294154 0.29222408 0.21836628 0.34856251]
[0.   0.25 0.5  0.75 1.  ]


In [3]:
import numpy as np

#1부터 10까지(미포함)의 2걸음 크기의 정수값 배열을 생성해보자.
arr = np.arange(1, 10, 2)
print(arr)
#모양이 (3, 4)인 모든 값이 1인 배열을 생성해보자.
arr2 = np.ones((3,4))
print(arr2)
#0과 1사이를 10등분하고자 할 때 등분값 배열을 생성해보자
arr3 = np.linspace(0, 1, 10)
print(arr3)

#배열 속성 출력
print(arr2)

print('size:', arr2.size) # 배열의 총 항목 개수
print('dtype:',arr2.dtype) # 배열의 각 개별 항목의 데이터 타입
print('shape:',arr2.shape) # 배열 형태
print('ndim:',arr2.ndim) # 배열의 축의 개수

#배열 인덱싱
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr4[0])
#배열명[시작 번호:끝 번호] : 인덱스가 시작 번호부터 (끝 번호-1)까지인 항목
print(arr4[0:2])

#예제2

#A행렬을 생성해보자.
A = np.array([[ 1, 2, 3, 4, 5], [ 6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]])
#A의 모양(shape)을 출력해보자.
print(A.shape)
#19보다 큰 값을 추출해보자.
print(A[A > 19])
#슬라이싱을 이용하여 [[1, 2], [6, 7]] 값을 추출해보자
print(A[0,0:2], A[1,0:2])
#슬라이싱을 이용하여 [[19, 20], [24, 25]] 값을 추출해보자.
print(A[3,3:5], A[4,3:5])
#슬라이싱을 이용하여 0축의 첫 번째 행과 두 번째 행을 추출해보자.
print(A[0:2, :])
#슬라이싱을 이용하여 1축의 마지막 열과 마지막 직전 열을 추출해보자.
print(A[:, -2:])

[1 3 5 7 9]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
size: 12
dtype: float64
shape: (3, 4)
ndim: 2
[1 2 3]
[[1 2 3]
 [4 5 6]]
(5, 5)
[20 21 22 23 24 25]
[1 2] [6 7]
[19 20] [24 25]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


In [14]:
import numpy as np
#A행렬 만들기
A = np.arange(1,37)
print(A)
B= A.reshape(3,3,4)
print(B)
#A행렬의 모양과 크기를 출력해보자
print(B.shape)
print(B.size)
#A의 모양을 (3,4,3)로 변경해보자
C= B.reshape(3,4,3)
print(C)
#A를 1차원 배열로 구성해보자
D= C.flatten()
print(D)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]
(3, 3, 4)
36
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


In [5]:
#두 배열에 대한 덧셈, 뺄셈, 크기 비교 연산 결과 출력
import numpy as np
arr1 = np.arange(1,5)
arr2 = np.ones(4)
print(arr1 , arr2)
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 > arr2)

[1 2 3 4] [1. 1. 1. 1.]
[2. 3. 4. 5.]
[0. 1. 2. 3.]
[False  True  True  True]


In [6]:
#배열에 2를 더하고, 2를 곱한 결과를 출력
import numpy as np
arr1 = np.random.randint(11, size=4)
print(arr1)
print(arr1 + 2)
print(arr1 * 2)


[ 3  1  1 10]
[ 5  3  3 12]
[ 6  2  2 20]


In [10]:
#‘국어’, ‘영어’라는 이름의 배열 생성
import numpy as np
국어 = np.array([20,30,60])
영어 = np.array([60,40,90])
print(국어)
print(영어)

#학생별 국어 점수와 영어 점수를 더한 총점과 평균을 구한 배열 생성
총점 = 국어 + 영어
평균 = 총점/2
print('총점=',총점)
print('평균=',평균)
print('국어 평균=',np.mean(국어))

[20 30 60]
[60 40 90]
총점= [ 80  70 150]
평균= [40. 35. 75.]
국어 평균= 36.666666666666664
